// <auto-generated />
using System;
using LibraryMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230602012719_defaultReturnedDate")]
    partial class defaultReturnedDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryMVC.Models.Book", b =>
                {
                    b.Property<string>("ISBN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("BookImgUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Pages")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ISBN");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ISBN = "9781847498571",
                            Author = "George Orwell",
                            BookImgUrl = "https://image.bokus.com/images/9781847498571_200x_1984-nineteen-eighty-four_haftad",
                            Language = "English",
                            Pages = 400,
                            PublishedDate = new DateTime(2021, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Alma Classics",
                            Title = "1984"
                        },
                        new
                        {
                            ISBN = "9780061120084",
                            Author = "Harper Lee",
                            BookImgUrl = "https://image.bokus.com/images/9780061120084_200x_to-kill-a-mockingbird_haftad",
                            Language = "English",
                            Pages = 336,
                            PublishedDate = new DateTime(1960, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Harper Perennial Modern Classics",
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            ISBN = "9780786222728",
                            Author = "J.K. Rowling",
                            BookImgUrl = "https://s1.adlibris.com/images/4410077/harry-potter-and-the-sorcerers-stone.jpg",
                            Language = "English",
                            Pages = 424,
                            PublishedDate = new DateTime(1999, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Thorndike Press Large Print",
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            ISBN = "9780743273565",
                            Author = "F. Scott Fitzgerald",
                            BookImgUrl = "https://s2.adlibris.com/images/2143197/great-gatsby-the-us-import-ed.jpg",
                            Language = "English",
                            Pages = 180,
                            PublishedDate = new DateTime(2004, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Scribner",
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            ISBN = "9780141199078",
                            Author = "Jane Austen",
                            BookImgUrl = "https://s1.adlibris.com/images/50780/pride-and-prejudice.jpg",
                            Language = "English",
                            Pages = 416,
                            PublishedDate = new DateTime(2012, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Penguin Books Ltd.",
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            ISBN = "9780007458424",
                            Author = "J.R.R. Tolkien",
                            BookImgUrl = "https://s1.adlibris.com/images/2764059/the-hobbit.jpg",
                            Language = "English",
                            Pages = 368,
                            PublishedDate = new DateTime(2012, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "HARPERCOLLINS PUBLISHERS",
                            Title = "The Hobbit"
                        },
                        new
                        {
                            ISBN = "9780316769488",
                            Author = "J.D. Salinger",
                            BookImgUrl = "https://s1.adlibris.com/images/658340/the-catcher-in-the-rye.jpg",
                            Language = "English",
                            Pages = 240,
                            PublishedDate = new DateTime(1991, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Little, Brown and Company",
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            ISBN = "9780006546061",
                            Author = "Ray Bradbury",
                            BookImgUrl = "https://image.bokus.com/images/9780006546061_200x_fahrenheit-451_haftad",
                            Language = "English",
                            Pages = 192,
                            PublishedDate = new DateTime(1993, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Harper Voyager",
                            Title = "Fahrenheit 451"
                        },
                        new
                        {
                            ISBN = "9780060254926",
                            Author = "Maurice Sendak",
                            BookImgUrl = "https://s1.adlibris.com/images/961645/where-the-wild-things-are.jpg",
                            Language = "English",
                            Pages = 32,
                            PublishedDate = new DateTime(2012, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "HarperCollins Children's Books",
                            Title = "Where the Wild Things Are"
                        },
                        new
                        {
                            ISBN = "9780441172719",
                            Author = "Frank Herbert",
                            BookImgUrl = "https://pictures.abebooks.com/isbn/9780441172719-us.jpg",
                            Language = "English",
                            Pages = 896,
                            PublishedDate = new DateTime(1965, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Ace Books",
                            Title = "Dune"
                        },
                        new
                        {
                            ISBN = "9789113071299",
                            Author = "Stieg Larsson",
                            BookImgUrl = "https://s1.adlibris.com/images/20938473/man-som-hatar-kvinnor.jpg",
                            Language = "Swedish",
                            Pages = 567,
                            PublishedDate = new DateTime(2015, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Norstedts Förlag",
                            Title = "Män som hatar kvinnor"
                        },
                        new
                        {
                            ISBN = "9780061122415",
                            Author = "Paulo Coelho",
                            BookImgUrl = "https://m.media-amazon.com/images/I/41ybG235TcL._SX329_BO1,204,203,200_.jpg",
                            Language = "Portuguese",
                            Pages = 208,
                            PublishedDate = new DateTime(1988, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "HarperOne",
                            Title = "The Alchemist"
                        },
                        new
                        {
                            ISBN = "9780316055444",
                            Author = "Donna Tartt",
                            BookImgUrl = "https://s2.adlibris.com/images/2756455/the-goldfinch-a-novel-pulitzer-prize-for-fiction.jpg",
                            Language = "English",
                            Pages = 784,
                            PublishedDate = new DateTime(2015, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Back Bay Books",
                            Title = "The Goldfinch"
                        },
                        new
                        {
                            ISBN = "9780446310789",
                            Author = "Phan Que Mai Nguyen",
                            BookImgUrl = "https://s2.adlibris.com/images/64998400/dar-askan-blommar.jpg",
                            Language = "Swedish",
                            Pages = 408,
                            PublishedDate = new DateTime(2023, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Historiska Media",
                            Title = "Där askan blommar"
                        },
                        new
                        {
                            ISBN = "9781501180989",
                            Author = "Stephen King",
                            BookImgUrl = "https://s1.adlibris.com/images/35482045/the-outsider.jpg",
                            Language = "English",
                            Pages = 576,
                            PublishedDate = new DateTime(2018, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Scribner Book Company",
                            Title = "The Outsider"
                        },
                        new
                        {
                            ISBN = "9780439023528",
                            Author = "Suzanne Collins",
                            BookImgUrl = "https://s1.adlibris.com/images/780283/the-hunger-games-hunger-games-book-one-volume-1.jpg",
                            Language = "English",
                            Pages = 384,
                            PublishedDate = new DateTime(2010, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Scholastic Press",
                            Title = "The Hunger Games"
                        },
                        new
                        {
                            ISBN = "9780553103540",
                            Author = "George R.R. Martin",
                            BookImgUrl = "https://s1.adlibris.com/images/206629/a-game-of-thrones.jpg",
                            Language = "English",
                            Pages = 704,
                            PublishedDate = new DateTime(1996, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Bantam Books",
                            Title = "A Game of Thrones"
                        },
                        new
                        {
                            ISBN = "9781035003792",
                            Author = "Cormac McCarthy",
                            BookImgUrl = "https://s2.adlibris.com/images/63511627/the-road.jpg",
                            Language = "English",
                            Pages = 336,
                            PublishedDate = new DateTime(2022, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Vintage International",
                            Title = "The Road"
                        },
                        new
                        {
                            ISBN = "9780141315195",
                            Author = "Anne Frank",
                            BookImgUrl = "https://s1.adlibris.com/images/1630222/the-diary-of-a-young-girl.jpg",
                            Language = "Dutch",
                            Pages = 464,
                            PublishedDate = new DateTime(1947, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Penguin Books",
                            Title = "The Diary of a Young Girl"
                        },
                        new
                        {
                            ISBN = "9781526604736",
                            Author = "Khaled Hosseini",
                            BookImgUrl = "https://s2.adlibris.com/images/44037491/kite-runner.jpg",
                            Language = "English",
                            Pages = 372,
                            PublishedDate = new DateTime(2003, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Riverhead Books",
                            Title = "The Kite Runner"
                        },
                        new
                        {
                            ISBN = "9781784161101",
                            Author = "Paula Hawkins",
                            BookImgUrl = "https://s2.adlibris.com/images/21218791/girl-on-the-train.jpg",
                            Language = "English",
                            Pages = 416,
                            PublishedDate = new DateTime(2015, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Random House UK",
                            Title = "The Girl on the Train"
                        },
                        new
                        {
                            ISBN = "9789100184728",
                            Author = "Stephen King",
                            BookImgUrl = "https://s1.adlibris.com/images/58348667/institutet.jpg",
                            Language = "Swedish",
                            Pages = 664,
                            PublishedDate = new DateTime(2020, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Albert Bonniers Förlag",
                            Title = "Institutet "
                        });
                });

            modelBuilder.Entity("LibraryMVC.Models.BorrowedBookList", b =>
                {
                    b.Property<int>("BorrowedBookListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BorrowedBookListId"));

                    b.Property<string>("BooksISBN")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("BorrowedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomersCustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FK_CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("FK_ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Returned")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReturnedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BorrowedBookListId");

                    b.HasIndex("BooksISBN");

                    b.HasIndex("CustomersCustomerId");

                    b.ToTable("BorrowedBookLists");

                    b.HasData(
                        new
                        {
                            BorrowedBookListId = 1,
                            BorrowedDate = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2023, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FK_CustomerId = 1,
                            FK_ISBN = "9789100184728",
                            Returned = true,
                            ReturnedDate = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowedBookListId = 2,
                            BorrowedDate = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2020, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FK_CustomerId = 2,
                            FK_ISBN = "9781784161101",
                            Returned = true,
                            ReturnedDate = new DateTime(2020, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowedBookListId = 3,
                            BorrowedDate = new DateTime(2022, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2022, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FK_CustomerId = 3,
                            FK_ISBN = "9781526604736",
                            Returned = true,
                            ReturnedDate = new DateTime(2022, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowedBookListId = 4,
                            BorrowedDate = new DateTime(2023, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FK_CustomerId = 4,
                            FK_ISBN = "9780439023528",
                            Returned = false
                        },
                        new
                        {
                            BorrowedBookListId = 5,
                            BorrowedDate = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2023, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FK_CustomerId = 5,
                            FK_ISBN = "9780316055444",
                            Returned = false
                        },
                        new
                        {
                            BorrowedBookListId = 6,
                            BorrowedDate = new DateTime(2023, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2023, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FK_CustomerId = 1,
                            FK_ISBN = "9789113071299",
                            Returned = false
                        });
                });

            modelBuilder.Entity("LibraryMVC.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Email = "john@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Phone = "1234567890"
                        },
                        new
                        {
                            CustomerId = 2,
                            Email = "jane@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            Phone = "9876543210"
                        },
                        new
                        {
                            CustomerId = 3,
                            Email = "michael@example.com",
                            FirstName = "Michael",
                            LastName = "Johnson",
                            Phone = "5555555555"
                        },
                        new
                        {
                            CustomerId = 4,
                            Email = "emily@example.com",
                            FirstName = "Emily",
                            LastName = "Brown",
                            Phone = "1111111111"
                        },
                        new
                        {
                            CustomerId = 5,
                            Email = "daniel@example.com",
                            FirstName = "Daniel",
                            LastName = "Davis",
                            Phone = "9999999999"
                        },
                        new
                        {
                            CustomerId = 6,
                            Email = "olivia@example.com",
                            FirstName = "Olivia",
                            LastName = "Taylor",
                            Phone = "2222222222"
                        },
                        new
                        {
                            CustomerId = 7,
                            Email = "james@example.com",
                            FirstName = "James",
                            LastName = "Clark",
                            Phone = "7777777777"
                        },
                        new
                        {
                            CustomerId = 8,
                            Email = "sophia@example.com",
                            FirstName = "Sophia",
                            LastName = "Lewis",
                            Phone = "3333333333"
                        },
                        new
                        {
                            CustomerId = 9,
                            Email = "david@example.com",
                            FirstName = "David",
                            LastName = "Walker",
                            Phone = "8888888888"
                        },
                        new
                        {
                            CustomerId = 10,
                            Email = "emma@example.com",
                            FirstName = "Emma",
                            LastName = "Wilson",
                            Phone = "4444444444"
                        });
                });

            modelBuilder.Entity("LibraryMVC.Models.BorrowedBookList", b =>
                {
                    b.HasOne("LibraryMVC.Models.Book", "Books")
                        .WithMany("BorrowedBookLists")
                        .HasForeignKey("BooksISBN");

                    b.HasOne("LibraryMVC.Models.Customer", "Customers")
                        .WithMany("BorrowedBookLists")
                        .HasForeignKey("CustomersCustomerId");

                    b.Navigation("Books");

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("LibraryMVC.Models.Book", b =>
                {
                    b.Navigation("BorrowedBookLists");
                });

            modelBuilder.Entity("LibraryMVC.Models.Customer", b =>
                {
                    b.Navigation("BorrowedBookLists");
                });
#pragma warning restore 612, 618
        }
    }
}
